project:
  type: website

website:
  title: "ISSS626-GAA"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu: 
          - text: "Geospatial Data Wrangling with R" 
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01a.html"
          - text: "Choropleth Mapping with R" 
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01b.html"
          - text: "1st Order Spatial Points Patterns Analysis Methods" 
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02a.html"
          - text: "2nd Order Spatial Points Patterns Analysis Methods"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02b.html"
          - text: "Spatio-Temporal Point Patterns Analysis"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
          - text: "Spatial Weights and Analysis"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
      - text: "In-class Exercise"
        menu: 
          - text: "In-class Exercise 3a"
            href: "In-class_Ex/In-class_Ex03/In-class_Ex03a.html"
          - text: "In-class Exercise 3b"
            href: "In-class_Ex/In-class_Ex03/In-class_Ex03b.html"
          - text: "In-class Exercise 4"
            href: "In-class_Ex/In-class_Ex04/In-class_Ex04.html"
      - text: "Take-home Exercise"
        menu:
          - text: "Geospatial Analytics for Public Good"
            href: "Take-home_Ex/Take-home_Ex01/Takehome_Ex01_remade.html"
      
    right:
      - href: index.qmd
        text: Home
      
format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true

editor: visual

