---
title: "In Class Exercise 5b"
format: html
author: "Erica Chan"
date: "27 September , 2025"
date-modified: "last-modified"
execute: 
  eval: false
  echo: true
  warning: false
  freeze: true
---

```{r}
pacman::p_load(tidyverse, sf, sfdep, tmap, plotly, Kendall)
```

read in data

```{r}
hunan <- st_read(dsn = "data/geospatial",
                 layer="hunan")
```

```{r}
GDPPC <- read_csv("data/aspatial/hunan_GDPPC.csv")
```

```{r}
GDPPC <- left_join(hunan, GDPPC)
```

create time series cube

```{r}
GDPPC_st <- spacetime(GDPPC, hunan, 
                      .loc_col="County",
                      .time_col="Year")
```

```{r}
is_spacetime_cube(GDPPC_st)
```

Deriving spatial weights

```{r}
GDPPC_nb <- GDPPC_st %>%
  activate("geometry") %>%
  mutate(nb = include_self(
    st_contiguity(geometry)),
    wt = st_inverse_distance(nb, 
                             geometry, 
                             scale = 1,
                             alpha = 1),
    .before = 1) %>%
  set_nbs("nb") %>%
  set_wts("wt")
  
```

```{r}
gi_stars <- GDPPC_nb %>% 
  group_by(Year) %>% 
  mutate(gi_star = local_gstar_perm(
    GDPPC, nb, wt)) %>% 
  tidyr::unnest(gi_star)
```

Mann-Kendall test

H~0~: No monotonic trend present

H~1~: Monotonic trend detected

```{r}
ehsa <- gi_stars %>%
  group_by(County) %>%
  summarise(mk = list(
    unclass(
      Kendall::MannKendall(gi_star)))) %>%
  tidyr::unnest_wider(mk)
head(ehsa)
```

cbg=gi\_
